// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC0r_9r0y9h5n92V7vlBiw9Vm1v2FUEtQ',
    appId: '1:74416417574:web:8df3f0b2a6370f62ec6fe7',
    messagingSenderId: '74416417574',
    projectId: 'attendance-guru-97a44',
    authDomain: 'attendance-guru-97a44.firebaseapp.com',
    storageBucket: 'attendance-guru-97a44.firebasestorage.app',
    measurementId: 'G-V7E730ZXK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1Bml4EHodWN18t_A-t-q-_ZR01MV2rI',
    appId: '1:74416417574:android:766b2586814ce69fec6fe7',
    messagingSenderId: '74416417574',
    projectId: 'attendance-guru-97a44',
    storageBucket: 'attendance-guru-97a44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjq6jMh6whGOeg3zsW7I1gS158y8issis',
    appId: '1:74416417574:ios:0fef3ffa087fa223ec6fe7',
    messagingSenderId: '74416417574',
    projectId: 'attendance-guru-97a44',
    storageBucket: 'attendance-guru-97a44.firebasestorage.app',
    iosBundleId: 'com.example.sihNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjq6jMh6whGOeg3zsW7I1gS158y8issis',
    appId: '1:74416417574:ios:0fef3ffa087fa223ec6fe7',
    messagingSenderId: '74416417574',
    projectId: 'attendance-guru-97a44',
    storageBucket: 'attendance-guru-97a44.firebasestorage.app',
    iosBundleId: 'com.example.sihNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC0r_9r0y9h5n92V7vlBiw9Vm1v2FUEtQ',
    appId: '1:74416417574:web:a96f664a3c31b7f4ec6fe7',
    messagingSenderId: '74416417574',
    projectId: 'attendance-guru-97a44',
    authDomain: 'attendance-guru-97a44.firebaseapp.com',
    storageBucket: 'attendance-guru-97a44.firebasestorage.app',
    measurementId: 'G-H5DF46EJMG',
  );
}
